### ISSUE TITLE
naftis pod状态不正确

### ISSUE THREAD

**Issue by cll011** [XiaoMi/naftis#107]
按照yaml文件部署后，查看pod，状态一直未能处于running状态，如图：
![image](https://user-images.githubusercontent.com/44308785/53324035-b9c2e000-391a-11e9-97d3-b39281d326cc.png)
然后依次查看events和logs后，仍不知道怎么解决，events和logs依次如下：
1. 第一个pod的events：Back-off restarting failed container；
 logs：panic: failed to connect database dial tcp 10.104.171.112:3306: connect: connection refused。
2. 第二个pod的events：pulling image "mysql:5.7.14"一直处于拉取状态，但是镜像已经拉取成功了；
logs：Error from server (BadRequest): container "naftis-mysql" in pod "naftis-mysql-7fcc6f9799-v68h4" is waiting to start: PodInitializing。
3. 第三个pod的events没有发现什么异常，logs如下：
![image](https://user-images.githubusercontent.com/44308785/53324271-58e7d780-391b-11e9-9793-f7025708484a.png)
4. 第四个pod和第二个pod的events和logs一样。
希望前辈们能帮我这个小菜鸟解决一下，先谢谢了。

**Comment by csdnshyang** [comment]
可能是pvc没有删除干净。
尝试执行 tool/cleanup.sh  清理一下资源，重新安装步骤安装一下。

**Comment by cll011** [comment]
> 可能是pvc没有删除干净。
> 尝试执行工具/ cleanup.sh清理一下资源，重新安装步骤安装一下。
> @ cll011

清理之后，mysql还是启动不了，一直处于pulling image的状态，但是镜像已经拉取下来了
