### ISSUE TITLE
部署naftis，我想用自己的mysql数据库，请问要改哪里？

### ISSUE THREAD

**Issue by xiaotao0511** [XiaoMi/naftis#114]
部署naftis，我想用自己的mysql数据库，请问要改哪里？

**Comment by xiaotao0511** [comment]
有看到修改mysql链接的地方，但是没看到账号，密码在哪里修改

**Comment by Newt0n** [comment]
https://github.com/XiaoMi/naftis/blob/master/config/in-local.toml#L11
