### ISSUE TITLE
回滚后并没有删除掉应用的yaml

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#16]
回滚后显示成功了，但是并没有删险掉已生效的任务

**Comment by sevennt** [comment]
@shinynz 执行 `kubectl exec -it naftis-api-0 -n naftis '/usr/app/naftis/bin/naftis-api' version` 贴下输出看看？

**Comment by shinynz** [comment]
Defaulting container name to naftis-api.
Use 'kubectl describe pod/naftis-api-0 -n naftis' to see all of the containers in this pod.
Version: a31e9324f55209474ccc087037e971990efb2085-dirty
GitRevision: a31e9324f55209474ccc087037e971990efb2085-dirty
User: leslie@ubuntu
GolangVersion: go1.11
BuildStatus: Modified
BuildTime: 2018-10-29--20:44:08

**Comment by sevennt** [comment]
@shinynz `./tool/cleanup.sh` 清除掉旧的 Naftis，更新下代码再部署试试。

**Comment by sevennt** [comment]
@shinynz 这个问题解决了么。

**Comment by shinynz** [comment]
新版本已修复此问题
