### ISSUE TITLE
服务太多，创建任务时下拉框变成这样了

### ISSUE THREAD

**Issue by luban250** [XiaoMi/naftis#17]
![error](https://user-images.githubusercontent.com/44805329/48063313-99ea9d80-e1ff-11e8-84f5-0e1bc4d9caa3.jpg)

**Comment by sevennt** [comment]
前端样式问题，稍后我提 PR 修复。

**Comment by luban250** [comment]
@sevennt 谷歌浏览器69版本啊

**Comment by sevennt** [comment]
@luban250 前端代码已更新，`./tool/cleanup.sh` 清除掉旧的 Naftis，再部署试试。

**Comment by luban250** [comment]
@sevennt 可以了，谢谢啦。下拉框可以支持下搜索吗？

**Comment by sevennt** [comment]
@luban250 已支持搜索，再试试。

**Comment by luban250** [comment]
@sevennt 还有个问题，我创建了个自定义模板，跟traffic shift一样，就是把reviews改变为了{.Host},创建模板任务时填完参数提交就报错了，报400，提示namespace参数为空

**Comment by sevennt** [comment]
@luban250 这个问题你再提个新的 issue，我先关闭这个 issue。
