### ISSUE TITLE
建议模版生成后还可以编辑

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#18]
建议模版生成后还可以编辑

**Comment by sevennt** [comment]
之前考虑过这个功能，不过由于已经执行的 task 会关联到相应的 tasktmpl，如果某个 tasktpml 在构造 task 后被修改，可能会造成已经执行的 task 和当前的 tasktmpl 不匹配。

因此我们考虑新增 task_tmpl_logs 表，同时对 task_tmpl 表增加 `revision` 字段，对 tasktmpl 进行版本控制，方案确定好后，会有 PR 提上来。
