### ISSUE TITLE
总服务数，总pod数的配置在哪里修改？是要修改namespaces的值吗？

### ISSUE THREAD

**Issue by FreddyShen** [XiaoMi/naftis#23]
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/20896372/48123590-42a70480-e2b5-11e8-9df2-d61f6863cb39.png">

有暴露出来的配置可以修改吗？ 我想显示指定的namespaces下的服务数量？ 

还请老师指点，感谢！

**Comment by sevennt** [comment]
@FreddyShen 
`总的服务数 = sum(k8s中的所有namespace的服务数) - sum(k8s自己的服务数) - sum(Istio自己的服务数) - sum(Naftis自己的服务数) `

总的pod数计算方法类似。

**Comment by sevennt** [comment]
@FreddyShen 你的 Naftis 中二者均为 0，表示你可能还没有部署任何除了 Istio 和 Naftis 以外的其他服务。

**Comment by sevennt** [comment]
Naftis 默认认为你部署的 Istio 的 namespace 是 `istio-system`。

如果你的 Istio 不是部署在这个 namespace 下，可以参考这个 https://github.com/XiaoMi/naftis/issues/14 配置。

**Comment by FreddyShen** [comment]
非常感谢，默认的是可以显示的，我准备更新一个新的版本，安装试试看：看到新添加了：supporting user-configurable Istio namespace && dynamically fetch Naf…

![image](https://user-images.githubusercontent.com/20896372/48126672-b3055400-e2bc-11e8-8f8f-f31754100280.png)

**Comment by sevennt** [comment]
@FreddyShen 好的，我先关闭这个 issue 了。关于这个 issue 如果你还有其他的问题，可以再打开。

**Comment by csdnshyang** [comment]
遇到了类似的问题。
能看到istio的服务。
但是其他的pod总数为0.
但是能有一些服务的痕迹。
见图。
![1546873013806](https://user-images.githubusercontent.com/4383037/50774888-a490e400-12cf-11e9-9236-2aee64028a89.jpg)

**Comment by csdnshyang** [comment]
是需要在安装完naftis之后，再部署新的服务才能采集到信息吗？
