### ISSUE TITLE
模版生成的字段点击编辑报js错

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#27]
![2](https://user-images.githubusercontent.com/15795798/48176362-a3cce780-e34a-11e8-909d-26e5caca9e0d.jpg)
![111](https://user-images.githubusercontent.com/15795798/48176363-a3cce780-e34a-11e8-801f-b37a3133a152.jpg)
模版生成的字段点击编辑报js错，请看图片吧

**Comment by sevennt** [comment]
前端 UI Select 组件问题，已联系相关开发处理中。

**Comment by sevennt** [comment]
@shinynz 应该已经修复了，再试试。

**Comment by ChuckyThh** [comment]
同样发现这个问题，我是直接使用镜像部署的，似乎并没有修复这个问题，是不是镜像没有更新 @sevennt

**Comment by sevennt** [comment]
@ChuckyThh 嗯，有可能镜像没有更新。刚发布了 `0.1.1`，试试看看。

**Comment by shinynz** [comment]
最新版问题已解决
