### ISSUE TITLE
mysql脚本insert语句缺少缺少一个字段

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#28]
mysql脚本insert语句缺少一个字段，语句中新增加的namespace字段在插入时少了一个字段插入不进报错
![Uploading menu.saveimg.savepath20181108134655.jpg…]()

**Comment by shinynz** [comment]
![11](https://user-images.githubusercontent.com/15795798/48180162-6c1b6b00-e35d-11e8-96ea-a884fa0d25b5.jpg)

**Comment by sevennt** [comment]
@shinynz 已移除相关 sql 语句，https://github.com/XiaoMi/naftis/pull/29/files。
