### ISSUE TITLE
web-ui的“服务管理”中看不到istio的服务

### ISSUE THREAD

**Issue by zhy1991** [XiaoMi/naftis#32]

**Comment by zhy1991** [comment]
2018/11/17 16:06:13 [error] 7#7: *8031 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.20.0.0, server: , request: "GET /prometheus/api/v1/query_range?query=sum(rate(istio_requests_total{response_code=~%224.*%22}[1m]))&amp;start=1542470413&amp;end=1542470713&amp;step=10 HTTP/1.1", upstream: "**http://10.68.239.176:9090**/api/v1/query_range?query=sum(rate(istio_requests_total{response_code=~%224.*%22}[1m]))&amp;start=1542470413&amp;end=1542470713&amp;step=10", host:

**Comment by zhy1991** [comment]
这个地址不是我环境里的

**Comment by sevennt** [comment]
你的意思是`服务管理`页面中没有 `istio-system` 这个 namespace 下的 istio 系统相关的服务，
还是说`服务管理`页面中没有部署在 `istio` 中的业务服务（比如 `bookinfo` 之类的）？

**Comment by zhy1991** [comment]
我创建了bookinfo的应用，但是在naftis 的web-ui中“服务概览”——>“服务管理”中什么都看不到。

**Comment by sevennt** [comment]
@zhy1991 你的 bookinfo 部署的命名空间是什么？`default` 么？

**Comment by zhy1991** [comment]
是部署在default空间的，为了更方便和您交流。能否添加一下我的qq（499839808），谢谢。

**Comment by sevennt** [comment]
从 k8s 获取 pods 数据超时，已修复，见https://github.com/XiaoMi/naftis/commit/582235ce168e4e4a28410c4b50bc620a68dbf3e1 。

更新下 Naftis 再试试。

**Comment by sevennt** [comment]
@zhy1991 已修复 Istio 诊断页面获取数据慢的问题，你可以切换到 0.1.4-rc5 测试下。
我关闭这个 issue 了，如果还是未能解决你的问题，你可以再打开。
