### ISSUE TITLE
编译时总是报错

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#43]
![menu saveimg savepath20181123163331](https://user-images.githubusercontent.com/15795798/48934085-a419d500-ef3d-11e8-9c1d-a9a9368fc4f8.jpg)

**Comment by sevennt** [comment]
@shinynz 你的 `$GOPATH` 是不是设置的有问题？
![image](https://user-images.githubusercontent.com/10843736/48934514-48504b80-ef3f-11e8-9674-f0467ebfa993.png)

**Comment by shinynz** [comment]
还是失败
![111](https://user-images.githubusercontent.com/15795798/48936404-cc0d3680-ef45-11e8-97a2-904f84ee0438.jpg)

**Comment by sevennt** [comment]
@shinynz 
```bash
echo $GOPATH
pwd
```
贴出来看下。

**Comment by shinynz** [comment]
![11](https://user-images.githubusercontent.com/15795798/48937218-640c1f80-ef48-11e8-9cd8-7503124641cd.jpg)
GOPATH现在对了但编译还是出错

**Comment by sevennt** [comment]
> @shinynz
> 
> ```shell
> echo $GOPATH
> pwd
> ```
> 
> 贴出来看下。

能让我看下这两个指令的输出么？

**Comment by shinynz** [comment]
![333](https://user-images.githubusercontent.com/15795798/48937637-bbf75600-ef49-11e8-9d5d-87e43358a4fd.jpg)

**Comment by sevennt** [comment]
你微信多少，我加你直接说吧。

**Comment by shinynz** [comment]
shinyn

**Comment by sevennt** [comment]
OK

**Comment by sevennt** [comment]
通过一下。

**Comment by shinynz** [comment]
找到原因是我的go标准包之前的没有清理干净，谢谢
