### ISSUE TITLE
执行任务时不支持指定命名空间

### ISSUE THREAD

**Issue by liutanrong** [XiaoMi/naftis#5]
在非默认命名空间执行任务后,回滚失败。(界面显示成功,实际未能回滚)

**Comment by li1191863273** [comment]
兄dei，这个可以自定义模板指定


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{.namespace}}
  name: {{.Host}}
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: {{.Host}}
        subset: {{.DestinationSubset1}}
      weight: {{.Weight1}}
    - destination:
        host: {{.Host}}
        subset: {{.DestinationSubset2}}
      weight: {{.Weight2}}

**Comment by sevennt** [comment]
@liutanrong 目前尚不支持自定义命名空间，可以用 @li1191863273 提供的模板变量的方式解决。

我们后续会考虑创建任务时，提供自定义 namespace 的功能，由用户设定任务执行的 namespace。

@liutanrong @li1191863273 有兴趣提交 PR _嘛？:D

**Comment by sevennt** [comment]
和 https://github.com/XiaoMi/naftis/issues/6 重复，集中在 https://github.com/XiaoMi/naftis/issues/6 中答复。
