### ISSUE TITLE
执行任务无法更新

### ISSUE THREAD

**Issue by li1191863273** [XiaoMi/naftis#6]
执行一个任务，再次执行无法覆盖，却提示成功

**Comment by Newt0n** [comment]
提供下前后执行的任务的模板配置？

**Comment by sevennt** [comment]
@li1191863273 执行下 `kubectl logs -f naftis-api-0 -n naftis naftis-api`，把日志贴出来看下？

**Comment by li1191863273** [comment]
[GIN] 2018/10/29 - 09:17:30 | 200 |      46.533µs |        10.1.0.1 |  GET     /api/probe/healthy

(/usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/storer/db/tasktmpl.go:150)
[2018-10-29 09:17:38]  [3.60ms]  SELECT * FROM `task_tmpls`  WHERE `task_tmpls`.`deleted_at` IS NULL AND ((1=1 and id in ('48')))
[1 rows affected or returned ]

(/usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/storer/db/tasktmplvar.go:121)
[2018-10-29 09:17:38]  [12.07ms]  SELECT * FROM `task_tmpl_vars`  WHERE (1=1 and task_tmpl_id = '48')
[6 rows affected or returned ]
[GIN] 2018/10/29 - 09:17:38 | 200 |   19.146205ms |       127.0.0.1 |  POST     /api/tasks
[naftis] (1) 2018-10-29 09:17:38 [INFO]  [getTaskStatus] emit succ user:admin room:admin
[GIN] 2018/10/29 - 09:17:40 | 200 |      58.887µs |        10.1.0.1 |  GET     /api/probe/healthy
[GIN] 2018/10/29 - 09:17:40 | 200 |      51.031µs |        10.1.0.1 |  GET     /api/probe/healthy
[naftis] (1) 2018-10-29 09:17:42 [INFO]  Created config fail config:virtual-service/istio/reviews error:virtualservices.networking.istio.io "reviews" already exists
2018-10-29T09:17:42.611642Z	warn	virtualservices.networking.istio.io "reviews" not found

(/usr/gopath/src/micode.be.xiaomi.com/info-arch/naftis/src/api/storer/db/task.go:40)
[2018-10-29 09:17:42]  [0.98ms]  INSERT INTO `tasks` (`created_at`,`updated_at`,`deleted_at`,`content`,`revision`,`operator`,`task_tmpl_id`,`service_uid`,`status`,`command`,`prev_state`) VALUES ('2018-10-29 09:17:42','2018-10-29 09:17:42',NULL,'apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: istio
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 50
    - destination:
        host: reviews
        subset: v2
      weight: 50
原来项目提供name: reviews，这个name是个固定值，不是变量
---
','1','admin','48','9c0eb435-d8f0-11e8-95fa-025000000001','2','0','')
[1 rows affected or returned ]
[naftis] (1) 2018-10-29 09:17:42 [INFO]  [getTaskStatus] emit succ user:admin room:admin
[GIN] 2018/10/29 - 09:17:50 | 200 |      56.857µs |        10.1.0.1 |  GET     /api/probe/healthy

**Comment by sevennt** [comment]
@li1191863273 你执行的是默认的 `TrafficShifting` 模板构建的任务把？你的 `bookinfo` 是部署在 `istio` 这个 namespace 下吗？

**Comment by li1191863273** [comment]
就是上面那个分流的模板，我加了一个命名空间
是部署在istio命名空间下面

**Comment by sevennt** [comment]
嗯，不过默认的 bookinfo 部署在 default 这个 namespace 下，你本地的 bookinfo 不是部署在 default 下吗？

**Comment by sevennt** [comment]
@li1191863273 如果参考 istio 文档，把 `bookinfo`  部署在 `default` 下，应该没啥问题。
要不你再确认下？

**Comment by li1191863273** [comment]
都是在istio空间里面
意思是现在所有的应用都放在default才能用？ 实际应用都是放在不同namespace里面的

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?&name=li1191863273&uid=li1191863273%40hotmail.com&ftlId=1&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ali1191863273%40hotmail.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
li1191863273

邮箱：li1191863273@hotmail.com


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2018年10月30日 17:51，Wei Zheng<mailto:notifications@github.com> 写道：

@li1191863273<https://github.com/li1191863273> 如果参考 istio 文档，把 bookinfo 部署在 default 下，应该没啥问题。
要不你再确认下？

**Comment by sevennt** [comment]
@li1191863273 看了下代码，目前确实只支持 `default` ，稍后我会提 PR fix掉。

**Comment by li1191863273** [comment]
手动点个赞

**Comment by sevennt** [comment]
@li1191863273 https://github.com/XiaoMi/naftis/pull/10/commits/331d8c06461374aebd5b93732d283fd827169762

**Comment by sevennt** [comment]
@li1191863273 已经提交了 PR，清理掉旧的 Naftis，再部署下试试。

**Comment by sevennt** [comment]
@li1191863273 如果没其他问题，我就关闭这个 issue 了。

**Comment by li1191863273** [comment]
好的
