### ISSUE TITLE
API容器重启次数很多

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#83]
![image](https://user-images.githubusercontent.com/15795798/49412498-8e12dc80-f7a7-11e8-9ddb-31c22ca3738a.png)

**Comment by sevennt** [comment]
应该是 k8s-config-reloader 的问题，目前已由 @lincolnzhou 移除，见 https://github.com/XiaoMi/naftis/pull/86。

**Comment by sevennt** [comment]
@shinynz 我关闭这个 issue 了，如果还有问题，你可以再打开。
