### ISSUE TITLE
服务拓扑看不到图

### ISSUE THREAD

**Issue by mawennan** [XiaoMi/naftis#87]
您好，现在生成服务拓扑是调用的servicegraph还是kiali。 我从kiali里是能看到拓扑图的。

**Comment by sevennt** [comment]
@mawennan 你的 istio 版本是多少？另外确认下 promehtues 服务是不是处于 Running 状态下？

**Comment by mawennan** [comment]
没有用release， 我的版本是Istio 1.1.0-snapshot.3 - November 2018 Release

**Comment by sevennt** [comment]
kiali 上能看到，naftis 里面看不到，是么？
另外首页的监控数据的图能看到吗？

**Comment by sevennt** [comment]
@mawennan F12，可否贴下 `/api/d3graph` 接口响应。

**Comment by mawennan** [comment]
![5](https://user-images.githubusercontent.com/4082983/49571644-d6cbc080-f974-11e8-9399-32222e5973de.png)

这是我F12的截图

**Comment by sevennt** [comment]
看下 Response

**Comment by mawennan** [comment]
kubectl -n naftis logs naftis-api-5686686b97-grvgs -f

> 
[GIN] 2018/12/06 - 08:35:50 | 200 |      65.402µs |   10.144.131.48 | GET      /api/probe/healthy
[GIN] 2018/12/06 - 08:35:50 | 200 |    3.000837ms |   10.144.131.48 | GET      /api/d3graph?source_namespace=default&source_workload=productpage-v1
[naftis] (1) 2018-12-06 08:35:50 [INFO]  [API] /api/diagnose Pods Status start ts:2018-12-06 08:35:50.364531865 +0000 UTC m=+2950.959507148 
[naftis] (1) 2018-12-06 08:35:50 [INFO]  [API] /api/diagnose Pods Status end ts:2018-12-06 08:35:50.364618618 +0000 UTC m=+2950.959593884 
[GIN] 2018/12/06 - 08:35:50 | 200 |    9.020527ms |   10.144.131.48 | GET      /api/pods/productpage-v1-854ff5ccbd-nwmv5

**Comment by sevennt** [comment]
我的意思是 F12 里面的 Response

**Comment by sevennt** [comment]
另外 Naftis 的版本是多少？

**Comment by mawennan** [comment]
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: http://localhost:8000
Connection: keep-alive
Content-Length: 24
Content-Type: text/plain; charset=utf-8
Date: Thu, 06 Dec 2018 08:33:19 GMT
Server: nginx/1.14.2

版本是 0.1.4-rc3: Merge pull request #86 from lincolnzhou/master

**Comment by sevennt** [comment]
@mawennan 
![image](https://user-images.githubusercontent.com/10843736/49572038-d849b880-f975-11e8-9f0f-6bc8d8ee1d7f.png)

**Comment by mawennan** [comment]
![7](https://user-images.githubusercontent.com/4082983/49572288-6aea5780-f976-11e8-9ae8-9916fac9b263.png)

**Comment by sevennt** [comment]
@mawennan 目前 Naftis 兼容的是 1.1.0-snapshot.2，有可能 1.1.0-snapshot.3 里面修改了 Prometheus 相关的 metrics 代码。

**Comment by sevennt** [comment]
@mawennan 我先看下 Istio 1.1.0-snapshot.3 相关变更，稍后会在这个 issue 里面答复你。

**Comment by mawennan** [comment]
好的 谢谢~

**Comment by breeze7086** [comment]
1.1.0-snapshot.1也看不到图
/api/d3graph的response也是空的{"nodes":[], "links":[]}

**Comment by silenceper** [comment]
istio 1.02 同样也看不到图

**Comment by lincolnzhou** [comment]
@mawennan @breeze7086 已解决，请更新到最新版0.1.4-rc4
