### ISSUE TITLE
创建任务时namespace列表中没有istio-system

### ISSUE THREAD

**Issue by denglouping** [XiaoMi/naftis#88]

**Comment by denglouping** [comment]
请问是不是把执行任务时可选的namespace中过滤掉了istio-system，

如果像默认的rate-limiting模板中事先写好namespace为istio-system的话执行会报错，查看ui pod的log发现插入的数据中namespace为default，而文件内容里仍写定为istio-system。

**Comment by sevennt** [comment]
1. 模板中定义的 {{ .Namespace }} 变量无效，会被分步表单 Namespace Select 元素选中的值给覆盖掉，由于 Select 默认值设置的为 default，所以实际创建任务的 Namespace 为 default。
2. 分步表单 Namespace Sleect 中的 Options 中，默认过滤掉了 istio-system, kube-system, naftis 等，你的应用场景是什么，一定需要在 istio-system 中执行 task 吗？

**Comment by denglouping** [comment]
暂时我只注意到官方doc中有提到在istio中应用的rate-limit配置会应用到整个服务网格，所以觉得直接过滤掉是否有些不太合适。

**Comment by sevennt** [comment]
@denglouping 可以，我们把 istio-system 从移除名单中清除掉。

**Comment by sevennt** [comment]
@denglouping 已更新，见 https://github.com/XiaoMi/naftis/pull/92 。
