### ISSUE TITLE
模版中的参数应用到系统时会丢失

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#93]
<img width="151" alt="05bc2e976a851bb59e61499209fa653" src="https://user-images.githubusercontent.com/15795798/50125954-e963c500-02a5-11e9-8cdc-d2ae7338964c.png">
<img width="368" alt="1037da5ba841c436a1fe20d7dffa897" src="https://user-images.githubusercontent.com/15795798/50125961-ee287900-02a5-11e9-84cc-d503e4224a34.png">
这个红框的参数会丢失

**Comment by sevennt** [comment]
@shinynz Istio 的版本是多少？可否提供下任务模板内容和任务内容？

**Comment by shinynz** [comment]
istio1.0.5版本
