### ISSUE TITLE
建议增加登陆超时，现在每次登陆后metrics超时了

### ISSUE THREAD

**Issue by shinynz** [XiaoMi/naftis#95]
建议增加登陆超时，现在每次登陆后metrics超时了需要退出登陆重新登陆才能获取数据

**Comment by sevennt** [comment]
@shinynz 登陆后 metrics 超时是什么意思？首页获取监控数据超时么？

**Comment by shinynz** [comment]
登陆后如果长时间不操作cookie没有超时重登，metrics就获取不到监控数据了，必须要手动logout再重登
